### ISSUE TITLE
Not using `${workspaceFolder}` in "typst-preview.fontPaths"

### ISSUE THREAD

**Issue by tiankaima** [Enter-tainer/typst-preview#107]
**Describe the bug**
In `settings.json`, `${workspaceFolder}` is not parsed in "typst-preview.fontPaths" but directly passed as string to typst, causing it unable to compile

**To Reproduce**
`settings.json`:

```json
{
    "typst-preview.fontPaths": [
        "${workspaceFolder}/fonts"
    ]
}
```

**Expected behavior**

Error message pops and no window opens.

**Package/Software version:**

VSCode version(Help -> About):
```plain
版本: 1.81.1 (Universal)
提交: 6c3e3dba23e8fadc360aed75ce363ba185c49794
日期: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 23.0.0
```

typst-preview extension version: `v0.7.4`

**Logs:**

typst-preview server log(Output Panel -> typst-preview):

```plain
2023-09-01T06:44:28Z INFO  typst_preview] Arguments: CliArguments {
        font_paths: [
            "${workspaceFolder}/fonts",
        ],
        root: Some(
            "***",
        ),
        data_plane_host: "127.0.0.1:0",
        control_plane_host: "127.0.0.1:0",
        static_file_host: "127.0.0.1:23627",
        dont_open_in_browser: true,
        enable_partial_rendering: true,
        input: "***/***.typ",
    }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/runner/.cargo/git/checkouts/typst.ts-bd03698c1f5efd74/3ba125d/compiler/src/font/system.rs:44:49
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: typst_ts_compiler::font::system::FontProfileRebuilder::search_file
   4: typst_ts_compiler::font::system::SystemFontSearcher::search_file
   5: typst_ts_compiler::system::<impl typst_ts_compiler::world::CompilerWorld<typst_ts_compiler::system::SystemCompilerFeat>>::new
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tokio::runtime::context::runtime::enter_runtime
   8: tokio::runtime::runtime::Runtime::block_on
   9: typst_preview::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

typst-preview client log(Help -> Toggle Developer Tools -> Console):
```plain
typst-preview process exited with code 101
```

**Additional context**

**Comment by Enter-tainer** [comment]
nice catch. should we replace these placeholder with acutal paths in config?

**Comment by Enter-tainer** [comment]
vscode doc said these variables are only supported in launch.json and tasks.json. We can support these vars though. But is it a common practice to do so?

**Comment by tiankaima** [comment]
> vscode doc said these variables are only supported in launch.json and tasks.json. We can support these vars though. But is it a common practice to do so?

I would think so, what's your recommendation on an opensource project to share its font?

**Comment by Enter-tainer** [comment]
For this specific case, I guess setting it to `./some/font/path` should work for now. But I'm not sure. Perhaps installing your font to some "standard directory" would make your life easier.

https://www.npmjs.com/package/vscode-variables is mentioned in issues you posted and it looks nice to me. I will fix this soonish.

**Comment by tiankaima** [comment]
if you mean:
```json
{
    "typst-preview.fontPaths": [
        "./fonts"
    ]
}
```
then the answer is still no. It still won't compile

**Comment by Enter-tainer** [comment]
> opensource project to share its font

Alright, I believe I understand your use case. You have a repository for typst containing fonts. I recommend instructing your users to install these fonts in a designated, standardized location.

This issue will be resolved, though.

**Comment by Myriad-Dreamin** [comment]
Another [enhancement](https://github.com/Enter-tainer/typst-preview/labels/enhancement) but not too related here. Noticed that it produces a unreadable error: "No such file or directory", I should link it to a very old issue https://github.com/Myriad-Dreamin/typst.ts/issues/59.

I was trying following `typst-cli`, https://github.com/typst/typst/blob/ca1096de78fe219d58c651defcdf4bfc93f6d7e9/crates/typst-cli/src/fonts.rs#L170, which just ignores missing files. But for font paths provided by users, I prefer to don't silently failed.

Regarding to typst 0.6.0 provided `typst::eval::Tracer` along with warning primitives, we can produce soft errors more easily now. We may log the real reason of "No such file or directory" and other warnings in diagnostics console to remind users more friendly, @Enter-tainer.

**Comment by Myriad-Dreamin** [comment]
For sharing font paths, there already an environment variable `TYPST_FONT_PATHS` in system user level since typst-preview 0.7.4. The searching orders follows https://github.com/typst/typst/pull/1847#issuecomment-1663310539.

would be also great for sharing font paths to have capability of inherit `typst-preview.fontPaths` options among different level of setting. I'm not sure whether we should have it, @Enter-tainer. I don't know whether vscode is too smart to join `typst-preview.fontPaths` in workspace, user and global setting files.

**Comment by Enter-tainer** [comment]
AFAICT in vscode, local settings simply override global ones so the idea of cascading config files may not work. Other parts looks good to me. Producing better error messages is a good point.
