### ISSUE TITLE
Resizing vscode panes is very laggy

### ISSUE THREAD

**Issue by WannesMalfait** [Enter-tainer/typst-preview#125]
Resizing panes in vscode causes the area of the preview window to change. The preview keeps getting updated while resizing, causing it to become very laggy.

**To Reproduce**
(See video as well)
1. Open a `.typ` file
2. Open the preview in a different pane.
3. Try resizing the code pane by dragging the separator with the mouse.
4. The resizing is very laggy.

https://github.com/Enter-tainer/typst-preview/assets/46323945/1331430e-1f57-4669-926f-75065e9551e4

**Expected behavior**
The preview doesn't cause the resizing to be laggy. (Using just the pdf viewer in vs code doesn't have this problem at all). I don't know enough of the technical implementation of this extension, to know what it "should" do, but I imagine it can postpone the (expensive) updates until the mouse is released again.

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.82.1
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585

Date: 2023-09-08T08:41:36.199Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.4.6-76060406-generic
```

typst-preview extension version: `v0.8.0`

**Comment by Enter-tainer** [comment]
PR #120 should resolve this issue a little bit. Please wait for the next release!
