### ISSUE TITLE
Zoom causes panel to scroll up when the ctrl+wheel event has a relatively large `event.pageY`

### ISSUE THREAD

**Issue by Enter-tainer** [Enter-tainer/typst-preview#128]
**Describe the bug**
as title
**To Reproduce**
Preview a long document such as pkuthss and scroll the very end of preview panel. Use ctrl+wheel to scroll it.

**Package/Software version:**

This at least affects v0.8.0 and v0.8.1

**Comment by ParaN3xus** [comment]
Same issue
