### ISSUE TITLE
Add ability to invert colors on the preview page in a web browser

### ISSUE THREAD

**Issue by Andrew15-5** [Enter-tainer/typst-preview#134]
Since Dark Reader is disabled... Well, I can't use it anymore (unless I change the source code). I use Okular to view PDF files, which has 3 color inversion methods that are generally look good. For preview, I'm currently using MuPDF which has one basic color inversion shortcut. With `typst-preview` I'm basically stuck with eye-burning white background (although I did found a cool extension that dims everything, including typst-preview and videos: https://mehmetb.github.io/dimmer/). The only workaround (besides modifying index.html) is to always include `#set page(fill: black); #set text(fill: white)` (which won't fix bright images).

I was thinking about either adding a flag `--no-ignore-dark-reader` (which is a pretty easy fix). Or create (find) some color inversion tool for the preview (or maybe some simple CSS rules).

**Comment by Enter-tainer** [comment]
you can set background color and text color in typst sourcecode, or inject your own css.

**Comment by Enter-tainer** [comment]
we prefer present the compile result "as-is", the same as official webapp. although you can customize it using custom css rules through browser extensions or something

**Comment by Enter-tainer** [comment]
adding a inversion filter might make sense, though

**Comment by Enter-tainer** [comment]
perhaps using something like this: https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/invert . we can add a cli flag to control this. as for dark reader, i remember it cause problems and doesnt correctly recognize texts so we disable it by default.

**Comment by Andrew15-5** [comment]
> as for dark reader, i remember it cause problems and doesnt correctly recognize texts so we disable it.

I don't know what are you talking about. I switched Dark Reader to Filter/Filter+ mode and the background was pitch black and the text was pure white. In Dynamic mode, text is dark and barely visible.

> perhaps using something like this: https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/invert

Yes, this is exactly what I had in mind (I've encountered it when was creating a patch for the Dark Reader). And it looks like every browser supports it: https://caniuse.com/?search=invert.

**Comment by Enter-tainer** [comment]
> I don't know what are you talking about. I switched Dark Reader to Filter/Filter+ mode and the background was pitch black and the text was pure white. In Dynamic mode, text is dark and barely visible.

thanks for elaborating this. we previous receive reports of "preview is blank" from multiple darkreader users.

**Comment by Andrew15-5** [comment]
I switched to pre dark reader commit and preview was indeed blank. But when I allowed the plugin in the most recent commit, then the preview was working as expected. I don't know if the problem was specifically with the dark reader.

**Comment by Andrew15-5** [comment]
...if you are using VS Code. Otherwise, you can modify source in several different ways to achieve the more or less same result.

**Comment by RaulDurand** [comment]
> A simple work-around can be achieved by inserting `filter: invert(1);` to `index,html`.
> 
> The file is at `~/.vscode/extensions/mgt19937.typst-preview-0.9.2-linux-x64/out/frontend/index.html` for linux.
> 
> ![image](https://private-user-images.githubusercontent.com/53819558/287568910-85987c62-3be6-4476-9503-acf6a63d63af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjgzNTAsIm5iZiI6MTcxMzEyODA1MCwicGF0aCI6Ii81MzgxOTU1OC8yODc1Njg5MTAtODU5ODdjNjItM2JlNi00NDc2LTk1MDMtYWNmNmE2M2Q2M2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDIwNTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNDFkMTVhZTA2OWQzZmZjZTNlN2UxZmI2NjIyNGQ3NTI3Y2JlMGI4ZDkxZWVlOTQ5Yjg4OTAxYzZiYjAwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qn0EdqZwCxru55JixmmDZ_abs9yLgKYabQlX6DxkX-U)

it seems that it does not work any more...

**Comment by Enter-tainer** [comment]
> > A simple work-around can be achieved by inserting `filter: invert(1);` to `index,html`.
> > 
> > The file is at `~/.vscode/extensions/mgt19937.typst-preview-0.9.2-linux-x64/out/frontend/index.html` for linux.
> > 
> > ![image](https://private-user-images.githubusercontent.com/53819558/287568910-85987c62-3be6-4476-9503-acf6a63d63af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjgzNTAsIm5iZiI6MTcxMzEyODA1MCwicGF0aCI6Ii81MzgxOTU1OC8yODc1Njg5MTAtODU5ODdjNjItM2JlNi00NDc2LTk1MDMtYWNmNmE2M2Q2M2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDIwNTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNDFkMTVhZTA2OWQzZmZjZTNlN2UxZmI2NjIyNGQ3NTI3Y2JlMGI4ZDkxZWVlOTQ5Yjg4OTAxYzZiYjAwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qn0EdqZwCxru55JixmmDZ_abs9yLgKYabQlX6DxkX-U)
> 
> it seems that it does not work any more...

you dont need this now. see pr link above
