### ISSUE TITLE
Preview suddenly goes blank

### ISSUE THREAD

**Issue by KronosTheLate** [Enter-tainer/typst-preview#137]
**Describe the bug**
In the last couple of weeks, I experience that the preview goes blank quite often, triggered by a recompilation. Sometimes subsequent recompilation will fix the window, but the guaranteed fix is to open a new preview, confirming that the document compiles just fine. This typically occurs as I am just typing text.

**Package/Software version:**
```plain
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:45:31.402Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-86-generic
```

typst-preview extension version: `v0.8.1`

**Logs:**

typst-preview server log(Output Panel -> typst-preview):
I am unable to figure out how to open this log.

typst-preview client log(Help -> Toggle Developer Tools -> Console):
The Console did not output anything different when things worked, compared to when they did not.

**Additional context**
[Here is a link to a video](https://drive.google.com/file/d/1PdtUF0CTRRxsLceFOMS-2-quVQLMr6Vq/view?usp=sharing) demonstrating the issue. I compile upon saving, so you can see when the compilation happens as the dot indicating unsaved changes dissapears. As the document contains some personal information, I want to delete the video as soon as possible. Let me know when you have what you need from the video.

**Comment by Enter-tainer** [comment]
my email is lwzbill666@gmail.com, pls stamp the permission request

**Comment by KronosTheLate** [comment]
> my email is [lwzbill666@gmail.com](mailto:lwzbill666@gmail.com), pls stamp the permission request

Done

**Comment by Enter-tainer** [comment]
it looks like the preview becomes blank when the file is saved?
we previously notice that when saving, vscode will first truncate the file to zero length, then write acutal data. the 'empty' state has chances to trigger typst compilation.

**Comment by KronosTheLate** [comment]
Oh, that could be it! It would explain the "symptoms", as the page goes blank but seems to compile fine (i.e. nothing has crashed).

However, it seems to be the case that the odds of getting a blank page are rather large, making the "compile on save" option useless. Would it be possible to add a delay to the compilation, or just a "while filesize(path) == 0; do nothing; end" loop, to avoid compiling empty files?

**Comment by KronosTheLate** [comment]
I would love to. I am unable to find the "download" button on the linked GitHub action, so I will need a little more installation instructions. Perhaps I could build the master branch from source?

**Comment by Enter-tainer** [comment]
You can scroll down and click on the file names. This will trigger download
<img width="1169" alt="image" src="https://github.com/Enter-tainer/typst-preview/assets/25521218/84a9a256-9356-4e81-8576-6d3ee55ee1a0">

**Comment by KronosTheLate** [comment]
After a few minutes, I have not has the issue occuring, so it seems to be fixed! I will close this, and reopen it if the issue reappears. Thanks a bunch ^_^

**Comment by Enter-tainer** [comment]
Cool! glad to see it has been fixed. I will release a new version later this day.
