### ISSUE TITLE
[Bug/FR] Scroll to cursor in preview scrolls too far down.

### ISSUE THREAD

**Issue by KronosTheLate** [Enter-tainer/typst-preview#139]
When I move the cursor in the .typ file, the preview scrolls so that the cursor-location is at the top of the preview of the PDF. In fact, I just found a case where the top line is barely _outside_ the preview.

I would find it much more useful to be able to toggle a setting that makes the preview put the cursor-location in the center of the preview, and I am often as interested in what is before as what comes after.

**Comment by Enivex** [comment]
Any progress on this? I find myself continually having to fight against the scrolling.

**Comment by Enter-tainer** [comment]
This should be a easy(? @Myriad-Dreamin  correct me if I'm wrong) fix, we may just add more offset in `window.scrollTo`.
