### ISSUE TITLE
Feature request: Make the preview tab remember scroll position when you switch from and back to it

### ISSUE THREAD

**Issue by yaksher** [Enter-tainer/typst-preview#142]
Currently, when you switch to another tab from a preview window, when you switch back, it's at the start of the file. This becomes pretty inconvenient if the file you're editing is very large, because in partial rendering mode it's currently slow to scroll to the end again or whatever.

**Comment by Enter-tainer** [comment]
it is hard because when a tab is not visible, vscode deactivates it. and when it is visible again, everything begins from scratch. 

but i agree it is good to have this feature

**Comment by yaksher** [comment]
That's fair; I'm not aware of the details of VS Code plugins. My thought was that the PDF preview extension somehow does support this, but maybe file display tabs have special privileges even if they're displaying a non-text file?

**Comment by Enter-tainer** [comment]
I will have a look on that. Perhaps this is not as hard as I imagined

**Comment by Enter-tainer** [comment]
related:
https://github.com/microsoft/vscode/issues/22995
https://github.com/microsoft/vscode/issues/27498
https://code.visualstudio.com/api/extension-guides/webview#retaincontextwhenhidden
