### ISSUE TITLE
Feature request: Display when the preview is working or has errored out somehow

### ISSUE THREAD

**Issue by yaksher** [Enter-tainer/typst-preview#144]
I've been recently getting into Typst and I've been trying to do some fancier stuff with Typst and with like, potential divergent queries but also just really slow queries and also sometimes it just has some weird errors and Typst LSP is bad at highlighting them because they're just on one line somewhere random, it would be nice to just have a little indicator that's like, a checkmark for successfully rendered, slash for working, x for errored out or whatever in the corner.

**Comment by Enter-tainer** [comment]
related: #69. This is a good point. we may provide some minimal status indicator

**Comment by Enter-tainer** [comment]
also related #133

**Comment by Enter-tainer** [comment]
We plan to add a icon in the status bar like what copilot did: 
<img width="85" alt="image" src="https://github.com/Enter-tainer/typst-preview/assets/25521218/ddc78af3-9d6a-424f-91a4-511cd25669c0">
