### ISSUE TITLE
Feature request: slide show mode for typst preview in browser

### ISSUE THREAD

**Issue by OrangeX4** [Enter-tainer/typst-preview#160]
Now there are some typst slide packages like Polylux that can be used to create simple and attractive slides.
However, the final PDF format slides generated by them do not support animation images such as GIFs, which has been a limitation.

The powerful typst Preview plugin renders to SVG instead of PDF, so it can actually support animation GIF images. Additionally, typst Preview already has a `Preview current file in browser` feature that can achieve a similar effect. However, this solution lacks good slide support, such as displaying only a single page and using keyboard for navigation.

I propose adding a query parameter `?slide=true` to the browser page, indicating that it has entered slide show mode. In this mode, only one page is displayed by default, the background color is black, and navigation is possible using `space`, `enter`, `left/right` and `up/down` keys. This solution has a relatively low implementation cost and can provide excellent slideshow effects.

Finally, typst Preview is indeed powerful and useful. Thank you for developing the extension. :-)

**Comment by OrangeX4** [comment]
It is awesome, thanks.

**Comment by yomannnn** [comment]
nice ... Many thanks ...
