### ISSUE TITLE
Will the name of the assets in each releases ever change?

### ISSUE THREAD

**Issue by chomosuke** [Enter-tainer/typst-preview#173]
Hi @Enter-tainer,

First of all, thank you very much for this wonderful piece of work!

I have ported typst-preview to Neovim with a Neovim plugin [chomosuke/typest-preview.nvim](https://github.com/chomosuke/typst-preview.nvim). This plugin downloads the latest typst-preview binary from the release assets. Before I go ahead and advertise my plugin on Reddit and the likes, it would be nice if you can confirm that the name of the assets will never change since my plugin depends on it.

Edit: I've also just realized that my plugin also depend on:
- No line break within a json object.
- The "Control plane server listening on: " INFO message.

Are those things okay to depend on? For the second one, if not, how can I better check when the server is listening on the websocket?

**Comment by Enter-tainer** [comment]
It really cool to see someone is porting typst-preview to more editors! thanks for you work!

> Will the name of the assets in each releases ever change?

Existing ones will never change. New ones will very unlikely to change unless we have a very good reason to do that. We will notify you if it is subject to change.

> This plugin downloads the latest typst-preview binary from the release assets

I'm not familar with nvim extension development but I guess manaully lock a version in source code might be slightly better. And you may update the version in your source code when typst-preview bumps.

> No line break within a json object.

Do you mean the json messages passing between the editor and the preview server? We currently use serde-json to serialize it. By default it doesn't pretty-print json.

> The "Control plane server listening on: " INFO message.

We also rely on that to grab port numbers.

**Comment by chomosuke** [comment]
Thank you for your swift reply!

> We will notify you if it is subject to change.

Thank you!

> And you may update the version in your source code when typst-preview bumps.

I will do that. This would allow me to test whether my plugin work with newer version of typst-preview too so that's another plus.

> But I suggest you use a proper json parser.

I shall copy some json parsing lua code into my repo then. It's slightly annoying with nvim plugin development since you can't really depend on third party library (can't use luarocks).
