### ISSUE TITLE
Zooming is very jumpy

### ISSUE THREAD

**Issue by Enivex** [Enter-tainer/typst-preview#183]
**Describe the bug**
If I use ctrl + mouse wheel to zoom, the preview "jumps".

https://github.com/Enter-tainer/typst-preview/assets/2191754/26a88324-c6dc-4580-9a8f-4271df32dde2

typst-preview extension version: `v0.9.0`

**Comment by Enivex** [comment]
Possibly the same issue as https://github.com/Enter-tainer/typst-preview/issues/128 ? Though this always happens for me.

**Comment by Enter-tainer** [comment]
Does it still happens in 0.9.0?

**Comment by Enivex** [comment]
> > typst-preview extension version: v0.7.3
> 
> Does it still happens in 0.9.0?

Sorry, yes, I'm on 0.9.0. I just copied 0.7.3 from the report template without checking, because I assumed it was the last one

**Comment by memeplex** [comment]
I still see this happening in:

- macOS Sonoma
- typst-preview v0.10.8

I wouldn't say that the discrete jumps are wrong (although a smoother behavior would be desirable), but they are difficult to accurately control by means of the trackpad. If jumps are going to be in discrete steps, it would be better to bind zoom to some keys.

**Comment by Enter-tainer** [comment]
smooth pinch to zoom is on my radar and will be implemented in future.

**Comment by dattito** [comment]
very important, it's really annoying and decreasing the satisfaction using this absolutely amazing and magical tool.
