### ISSUE TITLE
Feature request: configure log level of output

### ISSUE THREAD

**Issue by Corbie-42** [Enter-tainer/typst-preview#196]
If you click on the Typst Preview Status, you will see the logs. If an error occurred, the logs will be spammed with `DEBUG` and `INFO` messages and you have to scroll up, until you find the error message.

Please add an option to adjust the log level to the VS Code extension configuration.

**Comment by Enter-tainer** [comment]
we will make compile errors directly displayed in the vscode disgnostics panel in future. so typically dont need to check logs

**Comment by Myriad-Dreamin** [comment]
This is not an issue in tinymist anymore.
