### ISSUE TITLE
Zooming in the preview window is too sensitive using MacBook trackpad

### ISSUE THREAD

**Issue by sevesalm** [Enter-tainer/typst-preview#208]
**Describe the bug**
Zooming in the preview window in VSCode using MacBook trackpad is way too sensitive. Even a miniscule pinch gesture can cause huge zoom. Same when zooming out. It is very hard to be precise and the sensitivity is a lot higher than in any other apps. It is now barely usable. I'd make the zoom steps very roughly 80% smaller.

**To Reproduce**
Steps to reproduce the behavior (Library test):
1. Open the preview view.
2. Use 2-finger pinch gesture to zoom in or out.

**Expected behavior**
Zoom should work as expected with the same sensitivity as in other macOS applications.

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:16.874Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0```

typst-preview extension version: `v0.10.2`

**Other info**

MacBook Pro M1 Pro 16"
macOS 14.1.1

**Comment by Myriad-Dreamin** [comment]
All trackpads have similar issues. this is because trackpads have a different move pattern than mouses.

related: pdf.js ever solved the issue.

**Comment by sevesalm** [comment]
Thanks, it is definitely better now on my MacBook! There are still things to improve (it zooms always to the left edge, it has steps, it shows some drawing artifacts during zooming) but at least now it is a lot easier to get the desired zoom level and what is important: it is now fully usable 👍🏼

**Comment by Enter-tainer** [comment]
thank you! i've aware of the problems you mentioned. and we plan to refactor relevant code and continuely improve scale experience in future versions🚀
