### ISSUE TITLE
Current version v0.10.3 Preview in Browser no Response

### ISSUE THREAD

**Issue by JeffreyAnimal** [Enter-tainer/typst-preview#211]
**Bug description**
`Typst Preview: Preview current file in browser` does not work.
On downgrading to v0.10.2 the Command does work.

**To Reproduce**
v0.10.3
Firefox 121.0 (64-Bit)

Steps to reproduce:
1. Enter Command in VSCode `Typst Preview: Preview current file in browser`
2. Wait
3. Nothing happens

**Expected behavior**
1. Enter Command in VSCode `Typst Preview: Preview current file in browser`
2. Wait
3. Opening preview in Browser on local adress

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by Enter-tainer** [comment]
reproduced. This may because of recent refactors

**Comment by Enter-tainer** [comment]
0.10.4 fix this
