### ISSUE TITLE
sensitive scrolling

### ISSUE THREAD

**Issue by AlexKrachun** [Enter-tainer/typst-preview#238]
**Describe the bug**
In vscode I've cought extremely sensitive scrolling
**To Reproduce**
Steps to reproduce the behavior (Library test):
1. Declare a rust test 'fn test_xxx() { ... }' or typescript test 'it_should(function () { ... })'
2. Execute test function
3. See error

Or (Shell code):

1. Attach necessary resources to execute shell code
2. Put down some shell code 'cargo run --bin typst-ts-cli -- ...'
3. Execute shell code

**Expected behavior**

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.12-x64v4-xanmod1
```

typst-preview extension version: `v0.7.3`

**Logs:**

typst-preview server log(Output Panel -> typst-preview):
```plain

```

typst-preview client log(Help -> Toggle Developer Tools -> Console):
```plain

```

**Additional context**

**Comment by Myriad-Dreamin** [comment]
What do you mean by "sensitive scrolling"?

**Comment by Enter-tainer** [comment]
i think it's a known issue

**Comment by Enter-tainer** [comment]
<img width="279" alt="image" src="https://github.com/Enter-tainer/typst-preview/assets/25521218/cf864f06-bfe3-49e1-8990-fbeeb91b61d0">

I just did some test on my macbook pro and it seems that the touchpad will send events at a very high speed (maybe at framerate). Maybe we can keep a distance and only trigger scale once when the target distance is reached
