### ISSUE TITLE
Use a different toolbar icon from typst-lsp

### ISSUE THREAD

**Issue by Enter-tainer** [Enter-tainer/typst-preview#255]

**Comment by Enter-tainer** [comment]
Maybe we can reuse icon designed by @Parsifa1  in #239

**Comment by Enter-tainer** [comment]
This is consider low priority because we may integrate into tinymist in the future

**Comment by Myriad-Dreamin** [comment]
https://github.com/Myriad-Dreamin/tinymist/pull/462
