### ISSUE TITLE
Relative paths don't work in `typst-preview.fontPaths`

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Enter-tainer/typst-preview#259]
I have a configuration of `typst-preview.fontPaths`, it works with absolute paths:

```json
{
  "typst-preview.fontPaths": [
    "/home/user/work/typst/tutorial/assets/fonts",
    "/home/user/work/typst/tutorial/assets/typst-fonts"
  ]
}
```

But I do want to use relative paths so that I can commit it to my git repository.

```json
{
  "typst-preview.fontPaths": [
    "./assets/fonts",
    "./assets/typst-fonts"
  ]
}
```

**To Reproduce**

Use the configuration.

**Expected behavior**

Let relative paths work. Ideally we can also let vscode variables work.

**Package/Software version:**

typst-preview extension version: `v0.10.8`

**Comment by Enter-tainer** [comment]
But it's still interesting why relative path won't work 🤔

**Comment by Enter-tainer** [comment]
> But it's still interesting why relative path won't work 🤔

Maybe for `typst-preview` the `.` is `~/.cache/vscode/...`. I guess. I think this could be improved
