### ISSUE TITLE
Wrong smartquotes for Spanish

### ISSUE THREAD

**Issue by memeplex** [Enter-tainer/typst-preview#261]
**Describe the bug**

I'm observing this behavior that was fixed in Typst several months ago:

* https://github.com/typst/typst/issues/922
* https://github.com/typst/typst/pull/941

I don't quite understand the relationship between Typst and Typst.ts (which I assume this project uses). Do they share code or are completely different implementations? How does Typst.ts track fixes and changes in Typst?

I'm reporting the issue here after having read: https://enter-tainer.github.io/typst-preview/#label-Bug%20Report

**To Reproduce**

```
#set text(
  lang: "es",
)

"Hola"
```

<img width="127" alt="image" src="https://github.com/Enter-tainer/typst-preview/assets/2845433/bce8f4fb-8a28-4ee2-b82a-b047332e92ab">

**Expected behavior**

<img width="127" alt="image" src="https://github.com/Enter-tainer/typst-preview/assets/2845433/b45b10d3-d18f-4e67-a295-62d9443de29d">

**Package/Software version:**

VSCode version(File -> About):

```plain
Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:42:12.210Z (1 wk ago)
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
```

typst-preview extension version: `v0.10.8`

**Comment by memeplex** [comment]
I'm closing this because I think I was wrong, that the quotes for es-ES are actually ok, but what I wanted were the quotes for es-AR.

Anyway, if you could clarify the relationship between typst-preview, typst.js and typst itself I would be thankful. I've read that typst.js calls the typst compiler, but I'm not sure and, in that case, what version of the compiler?

**Comment by Enter-tainer** [comment]
As you mentioned, use `es-ar` would fix the problem.

```
#set text(
  lang: "es",
  region: "ar"
)

"Hola"

```

typst-preview is an application, depends on typst and typst.ts. They share most of the code, the only difference is the export part where pdf/svg/png is produced.

>  I've read that typst.js calls the typst compiler, but I'm not sure and, in that case, what version of the compiler?

cc @Myriad-Dreamin maybe this can be improved?

For typst-preview the mapping is simple at least for now. `v0.10.8` means typst `v0.10.0` and we only update patch version unless when upgrading to next typst version
