### ISSUE TITLE
Support Preview in Separate Window?

### ISSUE THREAD

**Issue by SchrodingerZhu** [Enter-tainer/typst-preview#263]
<img width="1440" alt="image" src="https://github.com/Enter-tainer/typst-preview/assets/20108837/aa851d5b-1b6a-4808-a53c-8e35d1d525bc">

Currently, preview does not work in separate window. This harms the experience of using Typst preview with multiple displays.

**Comment by Enter-tainer** [comment]
https://enter-tainer.github.io/typst-preview/vscode.html

preview in browser

**Comment by Myriad-Dreamin** [comment]
See that in readme.

> Open in browser: open the preview in browser, so you put it in another monitor.

Should we highlight it furthermore? I feel there are quite many people asking for that without aware of the description about "Open in browser".

**Comment by SchrodingerZhu** [comment]
Hi, all,

Thank you for the following up. 

I think so have put the question wrongly. I just want to mention that the preview session cannot be in a separate window split by vscode. Is it possible to support that? (Maybe it is disabled by vacode itself.)

**Comment by Enter-tainer** [comment]
i think it is vscode's limitation. currently it seems that it doesnt support dragging a webview into another window

**Comment by Enivex** [comment]
As a heads up, I believe this will be resolved with version 1.88 of vscode.

**Comment by Enter-tainer** [comment]
> As a heads up, I believe this will be resolved with version 1.88 of vscode.

It there an upstream tracking issue for this? I've searched before but I didn't find one

**Comment by Enivex** [comment]
> > As a heads up, I believe this will be resolved with version 1.88 of vscode.
> 
> It there an upstream tracking issue for this? I've searched before but I didn't find one

https://github.com/microsoft/vscode/issues/195715

**Comment by Enter-tainer** [comment]
It's supported in latest vscode now. 
![image](https://github.com/Enter-tainer/typst-preview/assets/25521218/09167678-e6c1-4905-b80e-04a4b5446afb)
