### ISSUE TITLE
`#sys.version` is displayed as 0.10.0 even though 0.11.0 features are available

### ISSUE THREAD

**Issue by nineff** [Enter-tainer/typst-preview#267]
**Describe the bug**
After the update of this extension to `v0.11.0-rc1 - [2024-03-10]`, typst documents containing `#sys.version` still display 0.10.0 instead of 0.11.0

**To Reproduce**
1. Create Typst Document with the content `#sys.version`
2. Launch preview
3. See error

**Expected behavior**
the official typst compiler displays the version as `0.11.0` ; 

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.87.1 (system setup)
Commit: 1e790d77f81672c49be070e04474901747115651
Date: 2024-03-06T00:21:36.258Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
```

typst-preview extension version: `v0.11.0-rc1 - [2024-03-10]`

**Comment by Enter-tainer** [comment]
upstream does this, i have no idea where. please kindly open the same issue in typst/typst

**Comment by Enter-tainer** [comment]
We've update to 0.11.0 now. So this is "fixed" now
