### ISSUE TITLE
grey linear gradient appears red with shadow in preview

### ISSUE THREAD

**Issue by nineff** [Enter-tainer/typst-preview#269]
**Describe the bug**
See title & screenshot. Left side is official typst output, right side is preview. 

**To Reproduce**
use the following code:
```typst
#show quote.where(block: true): it => {

    align(center)[
      #rect(
        radius: 2mm,
        inset: 5mm,
        width: 100%,
        fill: gradient.linear(luma(240), luma(210)),
      )[
        #place(top + left, dy: -7mm)[
          #rect(
            radius: 1mm,
            width: 7mm,
            height: 5mm,
            fill: luma(120),
          )[#text(size: 20pt, baseline: -1.3pt, fill: white, font: "Trebuchet MS")[”]]
        ]
        #v(2mm)
        #align(left)[#emph(it.body)]
        #if it.has("attribution") and it.attribution != none {
          align(right)[-- #it.attribution]
        }
      ]
    ]
  }  

#quote(attribution: "some latin dude, probably", block: true)[#lorem(50)]
```

**Expected behavior**
A grey gradient should prieview as grey, not red

**Package/Software version:*

typst-preview extension version: `v0.10.9` (0.11.0-rc1)

**Comment by nineff** [comment]
![Screenshot 2024-03-11 110032](https://github.com/Enter-tainer/typst-preview/assets/3100873/01f69160-374a-4b46-8463-a4a6f0ed5c5c)

**Comment by Enter-tainer** [comment]
i guess this is the same as #268

**Comment by Enter-tainer** [comment]
we confused the color space. will fix in next version

**Comment by Enter-tainer** [comment]
fixed in incoming(maybe 30min) version
