### ISSUE TITLE
Can't install it using VSCode 1.75.1

### ISSUE THREAD

**Issue by pbos-gitgub** [Enter-tainer/typst-preview#281]
**Describe the bug**
The extension can't installed using VSCode 1.75.1

See attached error message

VSCode version(Help -> About):
Version: 1.75.1

typst-preview extension version: `v0.11.3`

![Ablage_01](https://github.com/Enter-tainer/typst-preview/assets/98145560/07fccf45-ea0a-4d98-a6b8-356c059250ba)

**Comment by Enter-tainer** [comment]
Please update your vscode. Latest is 1.88.0
