### ISSUE TITLE
Preview differs from PDF when rendering SVG

### ISSUE THREAD

**Issue by T1mVo** [Enter-tainer/typst-preview#282]
**Describe the bug**
I was using [harbinger](https://github.com/typst-community/harbinger) to create boxes with a box-shadow and noticed that the preview differs from the final PDF.

Preview:
![image](https://github.com/Enter-tainer/typst-preview/assets/94936637/9462bd30-76b6-4e1f-a98c-2133540d4525)

PDF:
![image](https://github.com/Enter-tainer/typst-preview/assets/94936637/d27a62e8-9979-4575-9e3d-2c81c1b6b09c)

This does not seem like a bug in Typst itself as a SVG export looks fine in Inkscape but not Edge or Typst Preview.

SVG in Inkscape (hard to see the shadows but they are there):
![image](https://github.com/Enter-tainer/typst-preview/assets/94936637/3af52660-a83a-4cea-bba0-ad6a608e07fc)

**To Reproduce**
````typst
#import "harbinger/src/shadow-box.typ": shadow-box

#show raw.where(block: true): it => {
    pad(4pt)[
      #shadow-box(
        fill: white,
        shadow-fill: rgb(89, 85, 101),
        radius: 4pt,
        inset: 12pt,
        width: 100%,
        blur: 5,
        margin: 5,
        dy: 4pt,
        opacity: 0.2,
      )[
        #align(left)[
          #it
        ]
      ]
    ]
  }

```rs
pub fn main() {
  println!("Hello World");
}
```
````

**Expected behavior**

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.88.0 (user setup)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045
```

typst-preview extension version: `v0.11.3`

**Comment by Enter-tainer** [comment]
looks like it is creating a svg file to produce shadow effect. interesting

**Comment by Enter-tainer** [comment]
![image](https://github.com/Enter-tainer/typst-preview/assets/25521218/5db8a93a-af13-4e58-af9f-5b6438501278)

The crafted svg background doesn't looks like shadow in chrome. It also looks the same in official svg export. I think this is [harbinger](https://github.com/typst-community/harbinger)'s bug

**Comment by Enter-tainer** [comment]
I'm closing this issue because it looks like it's upstream's bug. I change the `5pt 5pt` to `5 5` and it works. see also https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stdDeviation

**Comment by Enter-tainer** [comment]
Please also report this bug to [harbinger](https://github.com/typst-community/harbinger)!
