### ISSUE TITLE
Feature request: enable the extension on typ language mode

### ISSUE THREAD

**Issue by adamanteye** [Enter-tainer/typst-preview#287]
I am not sure whether this has already been done or I am doing the wrong way. Apologies in advance.

I was searching for how to enable the typst-preview extension if and only if on `typ` language mode, like [enable a VS Code extension only for certain file types](https://stackoverflow.com/questions/66701175/can-i-enable-a-vs-code-extension-only-for-files-with-a-specific-extension-edit). As the extension seems to enable itself gloably in every VS code workspace. And I seemed to find no clue. All I know is that probably the developer can decide when to start typst-preview.

And again thanks for your impressive work!

**Comment by Enter-tainer** [comment]
> As the extension seems to enable itself gloably in every VS code workspace

how to check if an extension is enabled or not?

**Comment by Enter-tainer** [comment]
https://code.visualstudio.com/api/references/activation-events

this looks useful. i will add it

**Comment by adamanteye** [comment]
> > As the extension seems to enable itself gloably in every VS code workspace
> 
> how to check if an extension is enabled or not?

I find the icon "T" shows in the Activity Bar :)

**Comment by Enter-tainer** [comment]
> > > As the extension seems to enable itself gloably in every VS code workspace
> > 
> > how to check if an extension is enabled or not?
> 
> I find the icon "T" shows in the Activity Bar :)
> 

that's interesting. it doesnt appear for me. iirc it should only appear after you actually preview a typst file.

**Comment by adamanteye** [comment]
Perhaps it's because I have enabled `typst-preview.showInActivityBar`. My guess is if it activates on an actual typst file, then enabling `typst-preview.showInActivityBar` still won't make it appear constantly.

**Comment by Enter-tainer** [comment]
sorry i misread. i reproduced what you described

**Comment by Myriad-Dreamin** [comment]
> https://code.visualstudio.com/api/references/activation-events
> 
> this looks useful. i will add it

this is already deprecated. VSCode will activate the extension on generated hooks to events since about 1.71
