### ISSUE TITLE
Error when building with windows 11

### ISSUE THREAD

**Issue by Eismandel** [Enter-tainer/typst-preview#290]
**Code does not compile**
When running

`cargo install --git https://github.com/Enter-tainer/typst-preview`

I get the following error:

error: couldn't read src\index.html: The system can not find the file. (os error 2)
   --> src\lib.rs:116:20
    |
116 | const HTML: &str = include_str!("index.html");
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `typst-preview` (lib) due to 1 previous error

**To Reproduce**
Steps to reproduce the behavior (Library test):
1. run `cargo install --git https://github.com/Enter-tainer/typst-preview`

**Comment by Enter-tainer** [comment]
https://enter-tainer.github.io/typst-preview/dev.html
