### ISSUE TITLE
Syntax highlighting of multi-line comments

### ISSUE THREAD

**Issue by gamagan** [Enter-tainer/typst-preview#293]
Syntax highlighting does not work for multi-line comments.
This is on the latest version, as of today, in vscode.

![image](https://github.com/Enter-tainer/typst-preview/assets/9970152/a628bd83-8b8e-4cc3-bff0-896b8ae08eff)

**Comment by Enter-tainer** [comment]
this extension doesnt provide syntax highlighting. please see tinymist
