### ISSUE TITLE
File does not generated PDF unless it is selected

### ISSUE THREAD

**Issue by gamagan** [Enter-tainer/typst-preview#295]
I'm working on a document that is broken into a main file + multiple chapter files. The main file includes the chapter files. 

In vscode, I open the main file for preview. I can work on the included files (the chapters), and the changes are reflected in the preview window. That is good. However, if I want to preview generated PDF document (represented by the main file) in an external PDF editor (which I do a lot), then I have to manually select the main file in vscode and save that; otherwise, the PDF for the main file does not get updated. This includes not updating when using "Save All".

Is there a workaround for updating that main file PDF (which is the file being previewed) without having to explicitly select that file tab?

Thanks

**Comment by Enter-tainer** [comment]
sorry but this extension doesnt generate any pdf file. you may confuse this with other extensions like tinymist or typst-lsp
