### ISSUE TITLE
New install of VSCode, Typst LSP, Typst Preview. Preview doesn't work

### ISSUE THREAD

**Issue by wmeyer48** [Enter-tainer/typst-preview#303]
In a VM (VirtualBox 7) I have just installed VSCode. Then installed Typst LSP and Typst Preview,
Created a small file with two lines of content. Issued Typst Preview current file. Got error:
typst-preview process exited with code 3221225501

Note that although the preview fails, a PDF is produced.

[Typst Preview.log](https://github.com/user-attachments/files/16074191/Typst.Preview.log)

**Comment by Enter-tainer** [comment]
how much memory does your vm have?

**Comment by Enter-tainer** [comment]
https://github.com/janhq/jan/issues/2111

exited with code 3221225501 means that your processor doesnt have avx instruction support

**Comment by wmeyer48** [comment]
Hello,
I installed VSCodium in the same VM and it works fine. VM has 4GB of RAM. Running Windows 10.
Thanks,
    On Tuesday, July 2, 2024 at 07:04:37 PM CDT, Wenzhuo Liu ***@***.***> wrote:  
 
 


janhq/jan#2111

exited with code 3221225501 means that your processor doesnt have avx instruction support
