### ISSUE TITLE
Right-to-left text files are not displayed correctly when sentences is composed of rtl and ltr text

### ISSUE THREAD

**Issue by giladfarber** [Enter-tainer/typst-preview#304]
When using #set text(dir: rtl), the output file of the compiled text is messy, which means characters in math expressions and English sentences are switched up, mostly where spaces are present, when a line contains both rtl and ltr text.

**To Reproduce**
1. use at the start of the file:
    #set text(dir: rtl)
2. write a line using both rtl and ltr characters (for example: נראה ש-$lim_(n->oo) sqrt(n)-sqrt(n-1)=0$)

**Expected behavior**
the real time preview displays the text as intended. only the output file is messy

**Package/Software version:**
none

VSCode version(Help -> About):
```plain
Version: 1.90.1
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:44:54.914Z (3 wks ago)
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

typst-preview extension version:
v0.11.7

**Comment by Enter-tainer** [comment]
Can you try reproduce this in typst-cli or typst webapp? I suspect it's not within typst-preview scope.

**Comment by giladfarber** [comment]
I'm currently copying and pasting my files to the Typst website to export them, which it does without any issues

**Comment by Enter-tainer** [comment]
Can you post full code here so I can copy paste them?

**Comment by giladfarber** [comment]
sure, I'll also attach two photos, one is a file that I exported from Typst and the other is a file that the Typst Preview compiled.
this is from the Typst preview:
<img width="870" alt="Screenshot 2024-07-03 at 9 05 49" src="https://github.com/Enter-tainer/typst-preview/assets/115878393/79de6a3a-1740-4e18-bb0c-4951ced35da1">
this is from the Typst website:
<img width="835" alt="Screenshot 2024-07-03 at 9 07 24" src="https://github.com/Enter-tainer/typst-preview/assets/115878393/da91793e-3ec3-4116-b6de-5e0f47521948">

**Comment by giladfarber** [comment]
this is the code:


ומחדו״א 1 אנו יודעים שזהו טור מתכנס, לכן האינטגרל מתכנס. נראה לפי היינה שהגבול אינו אפס: ניקח את הסדרה $a_n=n$ ואת הסדרה $b_n = n+1/2^(n+1)$, ונקבל $lim_(n->oo) f(a_n)=0!=1/2=lim_(n->oo) f(b_n)$, ולכן הגבול אינו קיים ובפרט אינו אפס כנדרש.
\
*(ב)* ייתכן. לדוגמה, הפונקציה $g(x) = cases(0 space :x in.not ZZ, x space:x in ZZ)$ אינטגרבילית כיוון שבכל תת קטע סופי של האינטגרל נקבל שהאינטגרל שווה ל-0, כיוון שהוא מזדהה עם $integral 0$ למעט מספר נקודות סופי, אך הסדרה לא חסומה מלמעלה.
\
*(ג)* החל ממקום מסוים $N$ מתקיים: $0<=L-epsilon<=f(x)<=L+epsilon$, ואינטגרל שומר על אי שוויון חלש, לכן מתקבל $integral_N^oo (L-epsilon) dx<=integral_N^oo f(x)dx => oo<=integral_N^oo f(x)dx => integral_N^oo f(x)dx = oo$. אין פה סתירה לסעיפים הקודמים, כיוון שבהם בכל קרן אינסופית ניתן היה למצוא ערך קרוב עד כדי $epsilon$ ל-$0$, וכאן לכל $0<epsilon<L$ קיים $N$ שהחל ממנו כל ערך רחוק לפחות ב-$epsilon$ מ-$0$.
== שאלה 3:
$ integral_(-oo)^oo f^2(x)dx => [space.hair^(u=f^2(x))_(u'=2f(x)f'(x)) space^(v'=1)_(v=x)] = underbrace([x f^2(x)]_(-oo)^oo, =(plus.minus sqrt(|x|) f(x))^2=0) - integral_(-oo)^oo 2x f(x)f'(x)dx = 1 => $ 
$ => integral_(-oo)^oo x f(x)f'(x)dx = -1/2 $

**Comment by giladfarber** [comment]
this is the code:

`
ומחדו״א 1 אנו יודעים שזהו טור מתכנס, לכן האינטגרל מתכנס. נראה לפי היינה שהגבול אינו אפס: ניקח את הסדרה $a_n=n$ ואת הסדרה $b_n = n+1/2^(n+1)$, ונקבל $lim_(n->oo) f(a_n)=0!=1/2=lim_(n->oo) f(b_n)$, ולכן הגבול אינו קיים ובפרט אינו אפס כנדרש.
\
*(ב)* ייתכן. לדוגמה, הפונקציה $g(x) = cases(0 space :x in.not ZZ, x space:x in ZZ)$ אינטגרבילית כיוון שבכל תת קטע סופי של האינטגרל נקבל שהאינטגרל שווה ל-0, כיוון שהוא מזדהה עם $integral 0$ למעט מספר נקודות סופי, אך הסדרה לא חסומה מלמעלה.
\
*(ג)* החל ממקום מסוים $N$ מתקיים: $0<=L-epsilon<=f(x)<=L+epsilon$, ואינטגרל שומר על אי שוויון חלש, לכן מתקבל $integral_N^oo (L-epsilon) dx<=integral_N^oo f(x)dx => oo<=integral_N^oo f(x)dx => integral_N^oo f(x)dx = oo$. אין פה סתירה לסעיפים הקודמים, כיוון שבהם בכל קרן אינסופית ניתן היה למצוא ערך קרוב עד כדי $epsilon$ ל-$0$, וכאן לכל $0<epsilon<L$ קיים $N$ שהחל ממנו כל ערך רחוק לפחות ב-$epsilon$ מ-$0$.
== שאלה 3:
$ integral_(-oo)^oo f^2(x)dx => [space.hair^(u=f^2(x))_(u'=2f(x)f'(x)) space^(v'=1)_(v=x)] = underbrace([x f^2(x)]_(-oo)^oo, =(plus.minus sqrt(|x|) f(x))^2=0) - integral_(-oo)^oo 2x f(x)f'(x)dx = 1 => $ 
$ => integral_(-oo)^oo x f(x)f'(x)dx = -1/2 $`

**Comment by giladfarber** [comment]
and thank you :)

**Comment by Enter-tainer** [comment]
<img width="585" alt="image" src="https://github.com/Enter-tainer/typst-preview/assets/25521218/bd9c07b8-61d6-4aaa-a2cf-8102f04570cf">

Would you mind reduce previous code to a minimal example?

**Comment by giladfarber** [comment]
oh it's just a shortcut that I added to the file. here's the code without any shortcuts:
`

ומחדו״א 1 אנו יודעים שזהו טור מתכנס, לכן האינטגרל מתכנס. נראה לפי היינה שהגבול אינו אפס: ניקח את הסדרה $a_n=n$ ואת הסדרה $b_n = n+1/2^(n+1)$, ונקבל $lim_(n->oo) f(a_n)=0!=1/2=lim_(n->oo) f(b_n)$, ולכן הגבול אינו קיים ובפרט אינו אפס כנדרש.
\
*(ב)* ייתכן. לדוגמה, הפונקציה $g(x) = cases(0 space :x in.not ZZ, x space:x in ZZ)$ אינטגרבילית כיוון שבכל תת קטע סופי של האינטגרל נקבל שהאינטגרל שווה ל-0, כיוון שהוא מזדהה עם $integral 0$ למעט מספר נקודות סופי, אך הסדרה לא חסומה מלמעלה.
\
*(ג)* החל ממקום מסוים $N$ מתקיים: $0<=L-epsilon<=f(x)<=L+epsilon$, ואינטגרל שומר על אי שוויון חלש, לכן מתקבל $integral_N^oo (L-epsilon) dif x<=integral_N^oo f(x)dif x => oo<=integral_N^oo f(x)dif x => integral_N^oo f(x)dif x = oo$. אין פה סתירה לסעיפים הקודמים, כיוון שבהם בכל קרן אינסופית ניתן היה למצוא ערך קרוב עד כדי $epsilon$ ל-$0$, וכאן לכל $0<epsilon<L$ קיים $N$ שהחל ממנו כל ערך רחוק לפחות ב-$epsilon$ מ-$0$.
`

**Comment by giladfarber** [comment]
here's the code without any modifications that I added:
`ומחדו״א 1 אנו יודעים שזהו טור מתכנס, לכן האינטגרל מתכנס. נראה לפי היינה שהגבול אינו אפס: ניקח את הסדרה $a_n=n$ ואת הסדרה $b_n = n+1/2^(n+1)$, ונקבל $lim_(n->oo) f(a_n)=0!=1/2=lim_(n->oo) f(b_n)$, ולכן הגבול אינו קיים ובפרט אינו אפס כנדרש.
\
*(ב)* ייתכן. לדוגמה, הפונקציה $g(x) = cases(0 space :x in.not ZZ, x space:x in ZZ)$ אינטגרבילית כיוון שבכל תת קטע סופי של האינטגרל נקבל שהאינטגרל שווה ל-0, כיוון שהוא מזדהה עם $integral 0$ למעט מספר נקודות סופי, אך הסדרה לא חסומה מלמעלה.
\
*(ג)* החל ממקום מסוים $N$ מתקיים: $0<=L-epsilon<=f(x)<=L+epsilon$, ואינטגרל שומר על אי שוויון חלש, לכן מתקבל $integral_N^oo (L-epsilon) dif x<=integral_N^oo f(x)dif x => oo<=integral_N^oo f(x)dif x => integral_N^oo f(x)dif x = oo$. אין פה סתירה לסעיפים הקודמים, כיוון שבהם בכל קרן אינסופית ניתן היה למצוא ערך קרוב עד כדי $epsilon$ ל-$0$, וכאן לכל $0<epsilon<L$ קיים $N$ שהחל ממנו כל ערך רחוק לפחות ב-$epsilon$ מ-$0$.`

**Comment by Enter-tainer** [comment]
reproduced. which is... weird.. I will take closer look when i leave work. 

cc @Myriad-Dreamin 

<img width="610" alt="image" src="https://github.com/Enter-tainer/typst-preview/assets/25521218/331b0ea7-bddc-4e91-89df-8d6292c49b66">

**Comment by Myriad-Dreamin** [comment]
The preview's renderer is developed based on `typst_render` but I haven't seen any process to rtl text from my quick glance. We may debug the concrete code then.

**Comment by Enter-tainer** [comment]
previous reproduction is done on my m2 macbook

**Comment by Enter-tainer** [comment]
possibly related:

- https://github.com/typst/typst/issues/3696

**Comment by Myriad-Dreamin** [comment]
> possibly related:
> 
> * [Inline math fragments are reversed while text is set to an RTL language typst/typst#3696](https://github.com/typst/typst/issues/3696)

Does it mean that we might get it by having different default `lang`/`region` on different machines?

**Comment by giladfarber** [comment]
that got it fixed. thanks a lot
