### ISSUE TITLE
Feature request: Add option to set invert filter value

### ISSUE THREAD

**Issue by unit-of-inductance** [Enter-tainer/typst-preview#307]
# Feature Request
Currently the [invert filter uses a value of .933333](https://github.com/Enter-tainer/typst-preview/blob/971dbc7f63ba12af4497204e7c433e0ed62d89a4/addons/frontend/src/typst.css#L42). This results in slightly grayish output for originally white pages. On e.g. OLED displays, I prefer fully black colors when using dark mode. Could we add an option to customize this value?

**Comment by Enter-tainer** [comment]
hi, please kindly recreate this issue in tinymist. this repo is no longer updated and i should archive it soon.

**Comment by unit-of-inductance** [comment]
Okay, thank you!
