### ISSUE TITLE
Use typst-ws as a stantalone binary

### ISSUE THREAD

**Issue by Enter-tainer** [Enter-tainer/typst-preview#71]
Something like https://github.com/ItsEthra/typst-live, but with better performance. 

This could be advantageous for those who use other editors. Unfortunately, cross jumping will not be supported.

**Comment by Myriad-Dreamin** [comment]
Ideally you can still write a temp file to registry/lock the websocket's data plane port. For example, for a file "path/to/file.typ", creating a file at "path/to/.file.typst-preview.json" containing exact following bytes content: 
```json
{"version": "v1beta","data-plane-addr": "ws://localhost:26666"}
```

This would help those third-party editor plugins discover a preview service.
