### ISSUE TITLE
Failed to preview with figures on arm64 device

### ISSUE THREAD

**Issue by xing7yi** [Enter-tainer/typst-preview#77]
typst-preview could not work (render only a blank page) when a figure was inserted in version 0.6.4, while it works well in v0.6.3.

**Comment by Enter-tainer** [comment]
I think it is related to #75, we are investigate on this. For now you can stick to v0.6.3. Are you also using an arm64 device?

**Comment by xing7yi** [comment]
Yes, I am using a MacBook Air with an M2 chip based on the ARM architecture.

**Comment by Enter-tainer** [comment]
Thanks! I think this bug is related to some platform dependent operation in the serialization library we use. We have already replicate the bug on various arm64 cpus like m2pro and huawei kp920. I will mention in this issue when it gets fixed.

**Comment by xing7yi** [comment]
Thanks, that helps a lot.
