### ISSUE TITLE
Discard stale watch events

### ISSUE THREAD

**Issue by Enter-tainer** [Enter-tainer/typst-preview#78]
If compilation takes a lot of time, all recompile events should be discarded other than process them in order. Or to say, only the latest recompile request should be processed. Reported by aleph on discord.

**Comment by Enivex** [comment]
Shouldn't it instead finish the existing compilation before starting a new one? Otherwise it'll just never compile anything if you type quickly.

**Comment by Enter-tainer** [comment]
> Shouldn't it instead finish the existing compilation before starting a new one?

exactly
