### ISSUE TITLE
Preview button is gone when `typst-lsp` is not installed

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Enter-tainer/typst-preview#82]
This is possibly caused by the preview button not showing when the typst source files are not detected.

See typst language spec in typst-lsp https://github.com/nvarner/typst-lsp/blob/4b367b8773c643c9cc198a4b6f9fb3abe837372d/editors/vscode/package.json#L90.

**Comment by Enter-tainer** [comment]
Should we bundle the same json key-value(and logo?) into our package.json?

**Comment by Myriad-Dreamin** [comment]
> Should we bundle the same json key-value(and logo?) into our package.json?

I guessed root cause. You can reproduce it by disabling `typst-lsp`. I don't know whether it is legal to bundle a language spec multiple times.
