### ISSUE TITLE
defaultSettings.json does not list the valid options for configure scroll sync mode

### ISSUE THREAD

**Issue by Enivex** [Enter-tainer/typst-preview#87]
The file reads as follows:
```
	// Configure scroll sync mode.
	//  - never: Scroll preview to current cursor position when selection changes
	"typst-preview.scrollSync": "onSelectionChange",
```

Only "never" is listed, and this is not even the default value. The description is also wrong.

The issue seems to be here
https://github.com/Enter-tainer/typst-preview/blob/2f184f61943872ffa0c8995848e5ffff3f023f14/addons/vscode/package.json#L97
There is no description for never.

**Comment by Enter-tainer** [comment]
what is default setting.json? i remember i put everything related to config in package.json
![Screenshot_2023-08-18-18-15-08-456_com.github.android.jpg](https://github.com/Enter-tainer/typst-preview/assets/25521218/c446f8e3-9398-48c9-aad9-8157fb91b10a)

**Comment by Enter-tainer** [comment]
okay this should be something generated by vscode. So we just need update the enum description

**Comment by Enter-tainer** [comment]
but i still don't quite understand the issue title. when use vscode ui to edit config, there should exist a drop down menu, listing all valid options.

**Comment by Enivex** [comment]
> but i still don't quite understand the issue title. when use vscode ui to edit config, there should exist a drop down menu, listing all valid options.

I never use the UI to edit the the config. I edit my settings.json manually, informed by defaultSettings.json

**Comment by Myriad-Dreamin** [comment]
At least the `enumDescriptions` list is incomplete corresponding to the `enum` list. Looks like it must be one-to-one mapping, so the `onSelectionChange` is missing in the generated description.
