### ISSUE TITLE
TypstActor: failed to watch filesystem events

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Enter-tainer/typst-preview#96]
Platform: Linux x86
Version: v0.9.3 (latest)

I doubt that opening any files is triggering this error.
Panic without any hints, need more information.

```log
[2023-08-24T01:59:35Z ERROR typst_preview::actor::typst] TypstActor: failed to watch filesystem events
thread '<unnamed>' panicked at 'explicit panic', src/actor/typst.rs:110:13
```

https://github.com/Enter-tainer/typst-preview/blob/711ebbd3d6d55f0303dfd5628bd5fd1db4f799bb/src/actor/typst.rs#L108-L111

**Comment by Enter-tainer** [comment]
We should provide better error message, at least
